language: java
jdk:
  - openjdk8
install:
  - mvn install -Dgpg.skip=true -B -V
  - cd demo
  - gradle test
  - cd ..
after_success:
  - mvn jacoco:report
  - mvn codecov:upload
  - mvn coveralls:report
  - mvn codacy:coverage
